/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import Help.Clock;
import java.util.Calendar;
import javax.swing.JLabel;

/**
 *
 * @author dell
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("QUẢN LÝ ĐÀO TẠO");
        JLabel lblClock = new JLabel("New label");
        lblClock.setBounds(640, 0, 95, 24);
        pn_dh.add(lblClock);
        Clock clock = new Clock(lblClock);
        clock.start();
    }

    void clock() {
        try {
            while (true) {
                Calendar calendar = Calendar.getInstance();
                String hour = (calendar.getTime().getHours() > 9)
                        ? "" + calendar.getTime().getHours() + ""
                        : "0" + calendar.getTime().getHours();
                String minute = (calendar.getTime().getMinutes() > 9)
                        ? "" + calendar.getTime().getMinutes() + ""
                        : "0" + calendar.getTime().getMinutes();
                String second = (calendar.getTime().getSeconds() > 9)
                        ? "" + calendar.getTime().getSeconds() + ""
                        : "0" + calendar.getTime().getSeconds();
                lbl_clock.setText(hour + ":" + minute + ":" + second);
                Thread.sleep(1000);
            }
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        btn_out = new javax.swing.JButton();
        btn_end = new javax.swing.JButton();
        btn_CD = new javax.swing.JButton();
        btn_NH = new javax.swing.JButton();
        btn_KH = new javax.swing.JButton();
        btn_HV = new javax.swing.JButton();
        btn_DH = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pn_dh = new javax.swing.JPanel();
        lbl_clock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        btn_out.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_out.setIcon(new javax.swing.ImageIcon("D:\\hoc tap\\DUANMAU\\DA\\img\\dangxuat1.png")); // NOI18N
        btn_out.setText("Đăng xuất");
        btn_out.setFocusable(false);
        btn_out.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_out.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_out);

        btn_end.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_end.setIcon(new javax.swing.ImageIcon("D:\\hoc tap\\DUANMAU\\DA\\img\\ketthuc1.png")); // NOI18N
        btn_end.setText("Kết thúc");
        btn_end.setFocusable(false);
        btn_end.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_end.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_endActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_end);

        btn_CD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_CD.setIcon(new javax.swing.ImageIcon("D:\\hoc tap\\DUANMAU\\DA\\img\\chuyende1.png")); // NOI18N
        btn_CD.setText("Chuyên đề");
        btn_CD.setFocusable(false);
        btn_CD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_CD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_CD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CDActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_CD);

        btn_NH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_NH.setIcon(new javax.swing.ImageIcon("D:\\hoc tap\\DUANMAU\\DA\\img\\nguoihoc1.png")); // NOI18N
        btn_NH.setText("Người học");
        btn_NH.setFocusable(false);
        btn_NH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_NH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_NH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NHActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_NH);

        btn_KH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_KH.setIcon(new javax.swing.ImageIcon("D:\\hoc tap\\DUANMAU\\DA\\img\\khoahoc1.png")); // NOI18N
        btn_KH.setText("Khóa học");
        btn_KH.setFocusable(false);
        btn_KH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_KH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_KH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KHActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_KH);

        btn_HV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_HV.setIcon(new javax.swing.ImageIcon("D:\\hoc tap\\DUANMAU\\DA\\img\\hocvien1.png")); // NOI18N
        btn_HV.setText("Học viên");
        btn_HV.setFocusable(false);
        btn_HV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_HV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_HV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HVActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_HV);

        btn_DH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_DH.setIcon(new javax.swing.ImageIcon("D:\\hoc tap\\DUANMAU\\DA\\img\\hdsd.png")); // NOI18N
        btn_DH.setText("HƯỚNG DẪN");
        btn_DH.setFocusable(false);
        btn_DH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_DH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_DH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DHActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_DH);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 49));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\hoc tap\\DUANMAU\\DA\\img\\ong.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 260, 360));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 730, 400));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, -1));

        lbl_clock.setIcon(new javax.swing.ImageIcon("D:\\hoc tap\\DUANMAU\\DA\\img\\clock.png")); // NOI18N
        pn_dh.add(lbl_clock);

        getContentPane().add(pn_dh, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\hoc tap\\DUANMAU\\DA\\img\\trogiup2.png")); // NOI18N
        jLabel2.setText("Hệ quản lý đào tạo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 160, -1));

        jMenu1.setText("Hệ thống");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Đăng nhập");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trợ giúp");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_outActionPerformed

    private void btn_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_endActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_endActionPerformed

    private void btn_CDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CDActionPerformed

    private void btn_NHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NHActionPerformed

    private void btn_KHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_KHActionPerformed

    private void btn_HVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_HVActionPerformed

    private void btn_DHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CD;
    private javax.swing.JButton btn_DH;
    private javax.swing.JButton btn_HV;
    private javax.swing.JButton btn_KH;
    private javax.swing.JButton btn_NH;
    private javax.swing.JButton btn_end;
    private javax.swing.JButton btn_out;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_clock;
    private javax.swing.JPanel pn_dh;
    // End of variables declaration//GEN-END:variables
}
