/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.DAOKhoahoc;
import DAO.DAOchuyende;
import Model.ChuyenDe;
import Model.KhoaHoc;
import Model.Nhanvien;
import java.util.Date;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class KhoaHocGUI extends JInternalFrame {

    DAOchuyende daoCD = new DAOchuyende();
    static Nhanvien nvlog = new Nhanvien();
    List<ChuyenDe> lstCD = daoCD.lstchuyende();
    DAOKhoahoc khDAO = new DAOKhoahoc();
    DefaultTableModel tbmodel = new DefaultTableModel();
    int _index = 0;

    /**
     * Creates new form KhoaHocGUI
     */
    public KhoaHocGUI() {
        initComponents();
        setform();
        loadtb();
        loadtext();
    }

    public static void getnvlog(Nhanvien x) {
        nvlog = x;
    }

    private void setform() {
        for (ChuyenDe x : lstCD) {
            cbbchuyende.addItem(x.getNameCD());
        }
        ChuyenDe x = lstCD.get(0);
        txtchuyende.setText(x.getNameCD());
        txthocphi.setText(x.getHocphiCD() + "");
        txtthuongluong.setText(x.getThoiluongCD() + "");
        txthocphi.setEditable(false);
        txtchuyende.setEditable(false);
        txtthuongluong.setEditable(false);
        txtnguoitao.setText(nvlog.getName());
        txtnguoitao.setEditable(false);
        txtngaytao.setText(Help.FormatDate.dinhDangNgayThangNam(new Date()));
        txtngaytao.setEditable(false);
        btn_add.setEnabled(false);
        tbmodel = (DefaultTableModel) tb_nguoihoc.getModel();
    }

    private void loadtb() {
        tbmodel.setRowCount(0);
        for (KhoaHoc x : khDAO.getlistKh()) {
            tbmodel.addRow(new Object[]{x.getIdKh(), x.getThoiluong(), x.getHocphi(),
                x.getNgayKG(), x.getNguoitao(), x.getNgaytao()});
        }
    }

    private void loadtext() {
        KhoaHoc x = new KhoaHoc();
        x = khDAO.getlistKh().get(_index);
        txtchuyende.setText(x.getTenkh());
        txtkhaigiang.setText(x.getNgayKG());
        txthocphi.setText(x.getHocphi() + "");
        txtthuongluong.setText(x.getThoiluong() + "");
        txtngaytao.setText(x.getNgaytao());
        txtnguoitao.setText(x.getNguoitao());
        txtgichu.setText(x.getGhichu());
    }

    private void refresh() {
        txtkhaigiang.setText("");
        txtgichu.setText("");
        cbbchuyende.setSelectedIndex(1);
        ChuyenDe x = lstCD.get(0);
        txtchuyende.setText(x.getNameCD());
        txthocphi.setText(x.getHocphiCD() + "");
        txtthuongluong.setText(x.getThoiluongCD() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_nguoihoc = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtngaytao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtgichu = new javax.swing.JTextArea();
        btn_last = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_change = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_fist = new javax.swing.JButton();
        btn_prev = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        txtnguoitao = new javax.swing.JTextField();
        txtkhaigiang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtthuongluong = new javax.swing.JTextField();
        txtchuyende = new javax.swing.JTextField();
        txthocphi = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cbbchuyende = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Quản lý Khóa học");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));
        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tb_nguoihoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khóa học", "Thời lượng", "Học phí", "Khai giảng", "Tạo bởi", "Ngày tạo"
            }
        ));
        jScrollPane1.setViewportView(tb_nguoihoc);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("DANH SÁCH", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Chuyên đề:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Ngày tạo :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Học phí :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Ghi chú :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Người tạo :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txtngaytao.setText("dd/mm/yyyy");
        txtngaytao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtngaytaoMouseClicked(evt);
            }
        });
        jPanel2.add(txtngaytao, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 290, -1));

        txtgichu.setColumns(20);
        txtgichu.setRows(5);
        jScrollPane2.setViewportView(txtgichu);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 610, 70));

        btn_last.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_last.setText("|>");
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });
        jPanel2.add(btn_last, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 50, -1));

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_delete.setText("Xóa");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 70, -1));

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel2.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 70, -1));

        btn_change.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_change.setText("Sửa");
        btn_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeActionPerformed(evt);
            }
        });
        jPanel2.add(btn_change, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 70, -1));

        btn_refresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_refresh.setText("Mới");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel2.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 70, -1));

        btn_fist.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_fist.setText("<|");
        btn_fist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fistActionPerformed(evt);
            }
        });
        jPanel2.add(btn_fist, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 50, -1));

        btn_prev.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_prev.setText("<<");
        btn_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prevActionPerformed(evt);
            }
        });
        jPanel2.add(btn_prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 50, -1));

        btn_next.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_next.setText(">>");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        jPanel2.add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 50, -1));
        jPanel2.add(txtnguoitao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 300, -1));

        txtkhaigiang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtkhaigiangMouseClicked(evt);
            }
        });
        jPanel2.add(txtkhaigiang, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 290, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Khai giảng:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Thời lượng (giờ):");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        txtthuongluong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtthuongluongMouseClicked(evt);
            }
        });
        jPanel2.add(txtthuongluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 290, -1));

        txtchuyende.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(txtchuyende, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, -1));
        jPanel2.add(txthocphi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 300, -1));

        jTabbedPane3.addTab("CẬP NHẬT", jPanel2);

        jPanel1.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 700, 360));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbbchuyende.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbchuyendeItemStateChanged(evt);
            }
        });
        cbbchuyende.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbchuyendeMouseClicked(evt);
            }
        });
        cbbchuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbchuyendeActionPerformed(evt);
            }
        });
        jPanel4.add(cbbchuyende, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 540, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 580, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Chuyên đề:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtthuongluongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtthuongluongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtthuongluongMouseClicked

    private void txtkhaigiangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtkhaigiangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkhaigiangMouseClicked

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        if (_index<(tbmodel.getRowCount()-1)) {
            _index++;
            loadtext();
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prevActionPerformed
        if (_index>0) {
            _index--;
            loadtext();
        }
    }//GEN-LAST:event_btn_prevActionPerformed

    private void btn_fistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fistActionPerformed
        _index =0;
        loadtext();
    }//GEN-LAST:event_btn_fistActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        if (btn_add.isEnabled()) {
            btn_add.setEnabled(false);
            btn_change.setEnabled(true);
            btn_delete.setEnabled(true);
        } else {
            btn_add.setEnabled(true);
            btn_change.setEnabled(false);
            btn_delete.setEnabled(false);
            refresh();
        }
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeActionPerformed
        KhoaHoc x = new KhoaHoc();
        x.setGhichu(txtgichu.getText());
        x.setHocphi(Double.parseDouble(txthocphi.getText()));
        x.setManv(nvlog.getId());
        x.setMaCD(lstCD.get(cbbchuyende.getSelectedIndex()).getIdCD());
        x.setNgayKG(txtkhaigiang.getText());
        x.setNgaytao(txtngaytao.getText());
        x.setTenkh(txtchuyende.getText());
        x.setThoiluong(Integer.parseInt(txtthuongluong.getText()));
        if (x.getNgayKG().isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Moi nhap nagy khai giang");
            return;
        }
        if (Help.Checkloi.checkNgay(x.getNgayKG()) == false) {
            JOptionPane.showMessageDialog(rootPane, "Moi nhap dung dinh dang");
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn sua không?", "OK",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            khDAO.updateKH(x);
            JOptionPane.showMessageDialog(rootPane, "Đã sua");
        }
    }//GEN-LAST:event_btn_changeActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        KhoaHoc x = new KhoaHoc();
        x.setGhichu(txtgichu.getText());
        x.setHocphi(Double.parseDouble(txthocphi.getText()));
        x.setManv(nvlog.getId());
        x.setMaCD(lstCD.get(cbbchuyende.getSelectedIndex()).getIdCD());
        x.setNgayKG(txtkhaigiang.getText());
        x.setNgaytao(txtngaytao.getText());
        x.setTenkh(txtchuyende.getText());
        x.setThoiluong(Integer.parseInt(txtthuongluong.getText()));
        if (x.getNgayKG().isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Moi nhap nagy khai giang");
            return;
        }
        if (Help.Checkloi.checkNgay(x.getNgayKG()) == false) {
            JOptionPane.showMessageDialog(rootPane, "Moi nhap dung dinh dang");
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn them không?", "OK",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            khDAO.insertKH(x);
            JOptionPane.showMessageDialog(rootPane, "Đã them");
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int ma = khDAO.getlistKh().get(_index).getIdKh();
        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn them không?", "OK",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            khDAO.deleteKH(ma);
            JOptionPane.showMessageDialog(rootPane, "Đã xoa");
            if ((tbmodel.getRowCount()-_index)==1) {
                _index--;
            }
            loadtb();
            loadtext();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        _index = tbmodel.getRowCount() -1;
        loadtext();
    }//GEN-LAST:event_btn_lastActionPerformed

    private void txtngaytaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtngaytaoMouseClicked

    }//GEN-LAST:event_txtngaytaoMouseClicked

    private void cbbchuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbchuyendeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbchuyendeActionPerformed

    private void cbbchuyendeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbchuyendeMouseClicked

    }//GEN-LAST:event_cbbchuyendeMouseClicked

    private void cbbchuyendeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbchuyendeItemStateChanged
        int index = cbbchuyende.getSelectedIndex();
        ChuyenDe x = lstCD.get(index);
        txtchuyende.setText(x.getNameCD());
        txthocphi.setText(x.getHocphiCD() + "");
        txtthuongluong.setText(x.getThoiluongCD() + "");
    }//GEN-LAST:event_cbbchuyendeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoaHocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoaHocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoaHocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoaHocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhoaHocGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_change;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_fist;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_prev;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JComboBox<String> cbbchuyende;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable tb_nguoihoc;
    private javax.swing.JTextField txtchuyende;
    private javax.swing.JTextArea txtgichu;
    private javax.swing.JTextField txthocphi;
    private javax.swing.JTextField txtkhaigiang;
    private javax.swing.JTextField txtngaytao;
    private javax.swing.JTextField txtnguoitao;
    private javax.swing.JTextField txtthuongluong;
    // End of variables declaration//GEN-END:variables
}
