/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.DAOLogin;
import Model.Nhanvien;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class NhavienGUI extends javax.swing.JFrame {

    DefaultTableModel tbModel = new DefaultTableModel();
    DAO.DAOLogin nhanvienDAO = new DAOLogin();
    List<Nhanvien> _lstadd = new ArrayList<>();
    int _index = 0;

    /**
     * Creates new form NhavienGUI
     */
    public NhavienGUI() {
        initComponents();
        setform();
        groupRD();
        loadTb();
        settext();
    }

    private void setform() {
        tbModel = (DefaultTableModel) tb_nhanvien.getModel();
        btnthem.setEnabled(false);
        setLocationRelativeTo(this);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        if (tbModel.getRowCount() < 0) {
            btnthem.setEnabled(true);
            btnsua.setEnabled(false);
            btnxoa.setEnabled(false);
        }
    }

    private void groupRD() {
        ButtonGroup groupVaitro = new ButtonGroup();
        groupVaitro.add(rdnv);
        groupVaitro.add(rdtt);
        rdnv.setSelected(true);
    }

    private void loadTb() {
        tbModel.setRowCount(0);
        int i = 1;
        for (Nhanvien x : nhanvienDAO.lstLog()) {
            tbModel.addRow(new Object[]{
                i++,
                x.getId(),
                x.getMatkhau(),
                x.getName(),
                x.getChucvu() == 0 ? "Nhân viên" : "Trưởng phòng"
            });
        }
    }

    private String addNV(Nhanvien x) {
        if (x.getId().isBlank()) {
            return "Mã nhân viên không bỏ trống";
        }
        if (Help.Checkloi.checkmaNV(x.getId(), nhanvienDAO.lstLog()) > -1) {
            return "Mã nhân viên đã tồn tại";
        }
        if (x.getName().isBlank()) {
            return "Họ và tên không bỏ trống";
        }
        if (x.getMatkhau().isBlank()) {
            return "Mật khẩu không bỏ trống";
        }
        if (txtpw2.getText().equals(x.getMatkhau()) == false) {
            return "Nhập lại đúng mật khẩu mới";
        }
        if (JOptionPane.showConfirmDialog(rootPane, "Chắc chắn thêm không?", "Thông báo",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            _lstadd.add(x);
            return "OK";
        }
        return "";
    }

    private void settext() {
        Nhanvien x = new Nhanvien();
        x = nhanvienDAO.lstLog().get(_index);
        txtmaNv.setText(x.getId());
        txtname.setText(x.getName());
        txtpw.setText(x.getMatkhau());
        txtpw2.setText(x.getMatkhau());
        rdnv.setSelected(x.getChucvu() == 0);
        rdtt.setSelected(x.getChucvu() == 1);
    }

    private String suaNV() {
        Nhanvien x = new Nhanvien();
        List<Nhanvien> lsttepm = nhanvienDAO.lstLog();
        x = lsttepm.get(Help.Checkloi.checkmaNV(txtmaNv.getText(), lsttepm));
        x.setId(txtmaNv.getText());
        x.setName(txtname.getText());
        x.setMatkhau(txtpw.getText());
        x.setChucvu(rdnv.isSelected() == true ? 0 : 1);
        if (x.getName().isBlank()) {
            return "Họ và tên không bỏ trống";
        }
        if (x.getMatkhau().isBlank()) {
            return "Mật khẩu không bỏ trống";
        }
        if (txtpw2.getText().equals(x.getMatkhau()) == false) {
            return "Nhập lại đúng mật khẩu mới";
        }
        if (JOptionPane.showConfirmDialog(rootPane, "Chắc chắn sửa không?", "Thông báo",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            _lstadd.add(x);
            nhanvienDAO.updateNV(x);
            return "OK";
        }
        return "";
    }

    private void refresh() {
        txtmaNv.setText("");
        txtpw.setText("");
        txtpw2.setText("");
        txtname.setText("");
        rdnv.setSelected(true);
    }

    private Nhanvien getNVlog() {
        try {
            return (Nhanvien) Help.writeandread.read("D:\\hoc tap\\DUANMAU\\DA\\object.txt");
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtmaNv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpw = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpw2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rdtt = new javax.swing.JRadioButton();
        rdnv = new javax.swing.JRadioButton();
        btnlast = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnmoi = new javax.swing.JButton();
        btnfist = new javax.swing.JButton();
        btnprev = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_nhanvien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Quản lý người học");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Mã nhân viên :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));
        jPanel2.add(txtmaNv, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 420, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Mật khẩu :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        jPanel2.add(txtpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 420, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nhập lại mật khẩu:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        jPanel2.add(txtpw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 420, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Vai trò:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 420, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Họ và tên :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        rdtt.setText("Trưởng phòng");
        jPanel2.add(rdtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        rdnv.setText("Nhân viên");
        jPanel2.add(rdnv, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        btnlast.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnlast.setText(">|");
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });
        jPanel2.add(btnlast, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        btnthem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        jPanel2.add(btnthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        btnsua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });
        jPanel2.add(btnsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        btnxoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        btnmoi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnmoi.setText("Mới");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });
        jPanel2.add(btnmoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        btnfist.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnfist.setText("|<");
        btnfist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfistActionPerformed(evt);
            }
        });
        jPanel2.add(btnfist, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        btnprev.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnprev.setText("<<");
        btnprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprevActionPerformed(evt);
            }
        });
        jPanel2.add(btnprev, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        btnnext.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnnext.setText(">>");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });
        jPanel2.add(btnnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        jTabbedPane3.addTab("CẬP NHẬT", jPanel2);

        tb_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "stt", "Mã nhân viên", "Password", "Họ và tên", "Vai trò"
            }
        ));
        jScrollPane1.setViewportView(tb_nhanvien);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("DANH SÁCH", jPanel3);

        getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 550, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        if (btnthem.isEnabled()) {
            btnthem.setEnabled(false);
            btnsua.setEnabled(true);
            btnxoa.setEnabled(true);
            if (getNVlog().getChucvu() == 0) {
                btnxoa.setEnabled(false);
            }
            settext();
        } else {
            btnthem.setEnabled(true);
            btnsua.setEnabled(false);
            btnxoa.setEnabled(false);
            refresh();
        }
    }//GEN-LAST:event_btnmoiActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        Nhanvien x = new Nhanvien();
        x.setId(txtmaNv.getText());
        x.setName(txtname.getText());
        x.setMatkhau(txtpw.getText());
        x.setChucvu(rdnv.isSelected() == true ? 0 : 1);
        String tb = addNV(x);
        if (tb.equals("") == false) {
            JOptionPane.showMessageDialog(rootPane, tb);
        }
        if (tb.equals("OK")) {
            nhanvienDAO.insertNV(x);
        }
        loadTb();
        refresh();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        JOptionPane.showMessageDialog(rootPane, suaNV());
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprevActionPerformed

        if (_index > 0) {
            _index--;
            settext();
        }
    }//GEN-LAST:event_btnprevActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        if (_index < (nhanvienDAO.lstLog().size() - 1)) {
            _index++;
            settext();
        }
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
        _index = nhanvienDAO.lstLog().size() - 1;
        settext();
    }//GEN-LAST:event_btnlastActionPerformed

    private void btnfistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfistActionPerformed
        _index = 0;
        settext();
    }//GEN-LAST:event_btnfistActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Chắc chắn xóa không", "Thông báo",
                JOptionPane.YES_OPTION) == JOptionPane.YES_OPTION) {
            Nhanvien x = new Nhanvien();
            List<Nhanvien> lst = nhanvienDAO.lstLog();
            _index = Help.Checkloi.checkmaNV(txtmaNv.getText(), lst);
            x = lst.get(_index);
            nhanvienDAO.xoaNV(x);
            if (lst.size() - _index == 1) {
                _index--;
            }
            settext();
            loadTb();
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhavienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhavienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhavienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhavienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhavienGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfist;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnmoi;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprev;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JRadioButton rdnv;
    private javax.swing.JRadioButton rdtt;
    private javax.swing.JTable tb_nhanvien;
    private javax.swing.JTextField txtmaNv;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpw;
    private javax.swing.JTextField txtpw2;
    // End of variables declaration//GEN-END:variables
}
